name: Run Selenium and Google Sheets Scripts

on:
  schedule:
    # Executa o workflow quatro vezes ao dia
    - cron: '0 3 * * *'    # Executa às 00:00 BRT (03:00 UTC)
    - cron: '0 11 * * *'   # Executa às 08:00 BRT (11:00 UTC)
    - cron: '0 15 * * *'   # Executa às 12:00 BRT (15:00 UTC)
    - cron: '0 19 * * *'   # Executa às 16:00 BRT (19:00 UTC)
    - cron: '0 22 * * *'   # Executa às 19:00 BRT (22:00 UTC)
    - cron: '15 22 * * *' 
    - cron: '0 1 * * *'    # Executa às 22:00 BRT (01:00 UTC do próximo dia)
    
  workflow_dispatch:       # Permite execução manual

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install gspread pandas selenium chromedriver-autoinstaller openpyxl

      - name: Run Selenium script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python script-turma2.py

      - name: Run Google Sheets Update Script
        env:
          CREDENTIALS_JSON_CONTENT: ${{ secrets.CREDENTIALS_JSON_CONTENT }}
        run: python turma2_script_planilha.py

      - name: Upload Downloaded File
        uses: actions/upload-artifact@v3
        with:
          name: turma2_planilha_notas.xlsx
          path: ${{ github.workspace }}/turma2_planilha_notas.xlsx
