name: Run Selenium and Google Sheets Scripts

on:
  schedule:
    # Executa o workflow quatro vezes ao dia
    - cron: '0 0 * * *'    # Executa à meia-noite UTC
    - cron: '0 8 * * *'    # Executa às 8h UTC
    - cron: '0 12 * * *'   # Executa ao meio-dia UTC
    - cron: '0 16 * * *'   # Executa às 16h UTC
  workflow_dispatch:       # Permite execução manual

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Baixa o código do repositório

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Define a versão do Python

      - name: Install Chrome Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          pip install gspread pandas selenium

      - name: Run Selenium script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python script-turma2.py

      - name: Upload Downloaded File
        uses: actions/upload-artifact@v3
        with:
          name: turma2_planilha_notas.xlsx
          path: /github/workspace/turma2_planilha_notas.xlsx
